#!/usr/bin/bash

# git #########################
# Подсветка ветки git
function parse_git_branch {
  git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function proml {
  local        BLUE="\[\033[0;34m\]"
  local         RED="\[\033[0;31m\]"
  local      YELLOW="\[\033[0;33m\]"
  local   LIGHT_RED="\[\033[1;31m\]"
  local       GREEN="\[\033[0;32m\]"
  local LIGHT_GREEN="\[\033[1;32m\]"
  local  LIGHT_GRAY="\[\033[0;37m\]"
  case $TERM in
    xterm*)
    TITLEBAR='\[\033]0;\u@\h:\w\007\]'
    ;;
    *)
    TITLEBAR=""
    ;;
  esac

PS1="$PS1$YELLOW\$(parse_git_branch)$LIGHT_GRAY"
PS2='> '
PS4='+ '
}

proml
####################

function ga() {
    git add .
    git status
}

function gc(){
    git commit -m "$*"
}

alias gst='git status'
alias gpl='git pull'
alias gps='git push'


